service: mongo-atlas-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  user:
    handler: ./src/index.handler
    url: true
plugins:
  - serverless-offline
